### ISSUE TITLE
Meta-issue with left over tasks

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab-contrib/rise#1]
This is a reboot of #381 - in order to move forward on https://github.com/jupyter/notebook/issues/6220

The approach taken differs from #381 as it creates a stand-alone app (similarly to retrolab - JLab remix) in order to:
- Deal with the DOM manipulation induced by RevealJS that don't play nicely in webapp such JupyterLab
- Add the opportunity to spin a notebook focusing on slideshow experience

What it does:
- Add button in JupyterLab notebook toolbar to open the RISE view of the current notebook
- Support federated extension in RISE mode (in particular ipywidgets are working)
- Restructure completely the package to be a single python package with multiple npm packages to ship a single package for the classical notebook and JupyterLab
- Support `ipywidget`
- Run on Binder for the classical notebook and JupyterLab ~~(but failed to open the standalone app from JupyterLab)~~

What it partly do:
- Create a ugly slideshow with no configuration

What needs to be done:
- [ ] Improve styling
- [x] properly handle all kinds of cells (subslide, fragment, ...)
- [x] Render slideshow in side-by-side panel within JupyterLab 
- [x] ~~Create custom notebook factory to remove the toolbar~~ Explicitly dispose the toolbar (avoid dealing with specific factory)
- [x] ~~Turn off virtual rendering~~ Wait for fully rendering before converting to slideshow (placeholder cannot be removed due to DOM  hierarchy change for Reveal)
- [ ] Turn off heading collapse feat.
- [x] Check Jupyter Widget `interact`
- Implement as much features as possible from classical:
  - [x] Support RevealJS theming
  - [x] Support shortcuts
  - [x] Support Jupytext (not tested may already work)  
    PR opened: https://github.com/mwouts/jupytext/pull/877
  - [x] Dynamically load custom CSS
  - Deal with configuration:
    - [x] at JupyterLab level
    - [x] at notebook level
- x [out of scope] Allow to edit style info from cell toolbar (updating extension??)
- x [out of scope] [optional] Bring something like [split-cell classic extension](https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/splitcell/readme.html)
- [ ] Smart execution
- [ ] Documentation
- [ ] CI job to at least test it installs

Help will be really appreciate to cover the above points - don't hesitate to open PRs against this PR branch.

![rise_demo_20211120](https://user-images.githubusercontent.com/8435071/142733720-ee5ae7cb-0340-40c9-9067-c7a2d53748ac.gif)

**Comment by nthiery** [comment]
Tested here after a pip installation, and it worked smoothly for what I tried.

Thank you!!!

**Comment by vidartf** [comment]
This should probably be reviewed again, and individual tasks split into separate issues.
